version: '3'

services:

  null-more-front-end:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: null-more-front-end
    ports:
      - "80:80"
    networks:
      - null-more-network

networks:
  null-more-network:
    external: true
